### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yuusukealmal** [yuusukealmal/Aokana#1]
- [ ] `video_op` parse
- [ ] `video_ed` parse
- [ ] `video_yokoku` parse
